### ISSUE TITLE
mkfringeflat using deprecated astropy function

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/stistools#139]
`mkfringeflat.py` imports `block_reduce` from astropy, but that has been deprecated since astropy 5.0 (see [here](https://github.com/astropy/astropy/blob/v5.0/CHANGES.rst#L380)) 

The offending import is here. There may be more references to this, but I only encountered the error here.
https://github.com/spacetelescope/stistools/blob/master/stistools/defringe/mkfringeflat.py#L4

**Comment by sean-lockwood** [comment]
That should have been resolved in #135, but we haven't published a release with the fix yet.

@stscirij: Do you know the process for updating the release?

**Comment by sean-lockwood** [comment]
@jotaylor -
There's a slight distinction here.  The `block_reduce` function itself is not deprecated in Astropy, but rather the old path for the import was.

**Comment by jotaylor** [comment]
I was wondering about that. In the changelog, it does say "these deprecated functions were moved". Should they still be used, even if they are in a new location?

**Comment by sean-lockwood** [comment]
Given the warning text:
`block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement.`

I think the changelog text isn't quite right.

**Comment by jotaylor** [comment]
Probably much easier to change the import than find a new function :D

**Comment by jotaylor** [comment]
@sean-lockwood I assume this issue was fixed in stistools 1.4.2?

**Comment by sean-lockwood** [comment]
Yes, it should be.
