### ISSUE TITLE
Testing Phil's doppinfo replacement

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stistools#17]
I'm testing Phil's doppinfo Python replacement before I start moving it into stistools.  There are some differences in output between the two, so STIS team will have to determine if these are acceptable differences. Looks like the IRAF version updates the file no matter what, but with the Python version it's option to update these keywords (ORBITPER, DOPPZERO, DOPPMAG, and DOPPMAGV).

Here's my results from testing two different files:
File 1 - IRAF
![screen shot 2018-02-23 at 5 02 45 pm](https://user-images.githubusercontent.com/5287848/36619248-29694b40-18bc-11e8-8347-c5541f89509d.png)

 File 1 - Python
![screen shot 2018-02-23 at 5 03 08 pm](https://user-images.githubusercontent.com/5287848/36619259-32f825dc-18bc-11e8-9aa3-85f2bc688b18.png)

File 2 - IRAF
![screen shot 2018-02-23 at 5 13 02 pm](https://user-images.githubusercontent.com/5287848/36619440-d45c16c2-18bc-11e8-92f6-a98435a7209f.png)

File 2 - Python
![screen shot 2018-02-23 at 5 14 32 pm](https://user-images.githubusercontent.com/5287848/36619502-0e590560-18bd-11e8-8ccf-2834d137b29e.png)

**Comment by dougbrn** [comment]
Sorry for not looking at this until now!

So this python replacement currently can't access sci extensions beyond the first? I don't think it's important for us to be able to automatically compute doppler info for all available sci extensions, but having the flexibility to specify which extension to use for a given call of the function seems like something we'd want. Would that be something that is easy to add in as an optional argument?

**Comment by SaOgaz** [comment]
Looks like I updated the script to loop through all SCI extensions but forgot to update this issue. 👍

**Comment by dougbrn** [comment]
Ah, great. For the files above, things look good. I don't think the STIS team has a preference on optional header keyword updates, as long as it maintains the capability to do so. We can cover that in the stistools documentation.
