### ISSUE TITLE
new stistools release

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stistools#47]
Want to gather several updates into one release for the stis team to test.  This will include:

- [x] #46 
- [x] #18 
- [x] #2

**Comment by SaOgaz** [comment]
#46 is done! We had the old tests from the pandokia system which I have ported.  But will send e-mail update in a second.  Oh also, the mktrace changes are not gonna make it in.  Had some delays on that one.

**Comment by dougbrn** [comment]
The STIS team has had several members install and test this version of stistools. Based on the testing, everyone found it to be consistent in functionality and output (within a small tolerance) with the current version of stistools. Based on this, the STIS team signs off on this new stistools release.
