### ISSUE TITLE
inttag produced raw files generating errors with calstis

### ISSUE THREAD

**Issue by jkcarlberg** [spacetelescope/stistools#73]
Attempting to run raw files generated with inttag.py through calstis generates errors similar to the following:

> Imset 1  Begin 12:44:46 EDT
         HSTIO error 114:  Filename noflare_raw3.fits EXTNAME DQ EXTVER 1 CFITSIO status 0
   Sci array has wrong number of dimensions.
         Open failed.
        calstis0 failed.

This appears to be due to a missing card in the DQ extension's header. Near line 250, where the DQ header keywords are populated, the following should be added:
`hdu.header['PIXVALUE'] = 0`

**Comment by dougbrn** [comment]
PR #74 applies the above fix which I can confirm works, PR #74 has been merged. Thanks Joleen for finding this bug and investigating it!
